name: Fix Android Folder
on: [push]
permissions:
  contents: write
jobs:
  fix-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Re-create Android Folder
        run: |
          rm -rf android/
          flutter create . --platforms=android --org com.example
      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Upgrade Android to v2 embedding" || echo "No changes"
          git push
