name: Generate Android Folder
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Recreate Android Folder
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.example
      - name: Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add android/
          git commit -m "Add fresh Android v2 folder"
          git push
